######## Dr. Firoz Ahmed, University of Jeddah ##############
# The program to create a volcano plot of Differentially Expressed Genes based 
# upon Log2F, and adj.p.value. 

library(EnhancedVolcano)
library(dplyr)

# Read the DEGs table, col1: Gene, col2: log2FC, col6: adj.P.Val
# The file "DEG_results_Primary_Tumor_Recurrent_Tumor_vs_Normal_Tissue_Solid_Tissue_Normal.csv" was generated by "Xena_DE_Analysis_Pipeline"
res <- read.csv("DEG_results_Primary_Tumor_Recurrent_Tumor_vs_Normal_Tissue_Solid_Tissue_Normal.csv", header = TRUE)

res2<-res[,c(1,2,6)]

# Add a new column  with "log.adj.P.Val" containing -log10(adj.p.value)
res3<-res2 %>% mutate(log.adj.P.Val=-log10(adj.P.Val))


# to check a gene and its records
filter(res3, Gene == "DDX3Y")

# generate a figures
jpeg(file="volcano_plot.jpeg",
width=10, height=10, units="in", res=600)

EnhancedVolcano(res3,
    lab = res3[,1], # Gene Name
    x = 'log2FC',   # log2FC of a gene
    y = 'adj.P.Val', # The 'adj.P.Val' values converted to the '-Log10(adj.P.Val)' automatically
    ylab = '-Log10(adj.P.Val)', # y contains '-Log10(adj.P.Val)', not  adj.P.Val
    pCutoff = 0.001,  
    FCcutoff = 2, 
    #labSize = 3.0,
    #pointSize = 2.0
    )

dev.off()
